import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
  size = 18.0
  normal =  { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
  bold = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
  italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
  bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

[window]
  padding = { x = 20, y = 30 }
  dimensions = { columns = 125, lines = 32 }
  decorations = "transparent"
  opacity = 1.0
  blur = true
  option_as_alt = "OnlyLeft"

[env]
term = "xterm-256color"

[selection]
  save_to_clipboard = true
